services:
  - type: web
    name: spainroom-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn codigo_flask:app --host 0.0.0.0 --port $PORT --proxy-headers
    autoDeploy: true
